### ISSUE TITLE
Change image stocks for symposia

### ISSUE THREAD

**Issue by davieiycode** [bppugm/icst-2019#2]

**Comment by imalavins** [comment]
1. Computer and Information Technology:
https://www.pexels.com/photo/person-using-silver-macbook-pro-1181467/
https://pixabay.com/en/coding-programming-working-macbook-924920/
https://www.pexels.com/photo/black-and-silver-laptop-computer-on-round-brown-wooden-table-1181243/
https://pixabay.com/en/monitor-binary-binary-system-1307227/
https://pixabay.com/en/technology-developer-continents-3435575/
https://pixabay.com/en/robot-artificial-intelligence-2167836/

2. Electronics, Communication, Control, and Instrumentation
https://www.pexels.com/photo/personal-computer-motherboard-4316/
https://www.pexels.com/photo/black-transistor-beside-capacitor-163100/
https://www.pexels.com/photo/bandwidth-close-up-computer-connection-1148820/
https://pixabay.com/en/block-chain-personal-shaking-hands-2850276/

3. Environmental and Earth Science
https://pixabay.com/en/international-space-station-view-1176518/
https://www.pexels.com/photo/ball-shaped-blur-close-up-focus-346885/
https://www.pexels.com/photo/earth-space-cosmos-5439/


4. Life Sciences, Materials, and Applied Chemistry
https://www.pexels.com/photo/high-angle-view-of-a-man-256381/
https://www.pexels.com/photo/clear-water-drops-132477/
https://www.pexels.com/photo/two-test-tubes-954585/

**Comment by davieiycode** [comment]
Symposia images by [Ars Electronica](https://flic.kr/p/NLBeFd) [(CC BY-NC-ND 2.0](https://creativecommons.org/licenses/by-nc-nd/2.0/)), [Ched Cheddles](https://flic.kr/p/9773UW) [(CC BY-NC-ND 2.0](https://creativecommons.org/licenses/by-nc-nd/2.0/)), [Kreemerz](https://flic.kr/p/27f3hV5) [(CC BY 2.0](https://creativecommons.org/licenses/by/2.0/)), and [NASA's Marshall Space Flight Center](https://flic.kr/p/UyzZWb) [(CC BY-NC 2.0](https://creativecommons.org/licenses/by-nc/2.0/)).

**Comment by imalavins** [comment]
Mechanical and Industrial 
![8502176733_bb6e075124_o](https://user-images.githubusercontent.com/4149578/53059736-829f9980-34ea-11e9-8b39-a76826b4a99b.jpg)

[<a data-flickr-embed="true"  href="https://www.flickr.com/photos/sharonmeyer/8978839883/" title="Metal Gear"><img src="https://farm3.staticflickr.com/2887/8978839883_c7a731f9a3_k.jpg" width="2048" height="1360" alt="Metal Gear"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>](url)

[<a data-flickr-embed="true"  href="https://www.flickr.com/photos/tonyfx/43748024241/" title="Gears"><img src="https://farm2.staticflickr.com/1791/43748024241_d0cef3ce82_k.jpg" width="2048" height="1377" alt="Gears"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>](url)

**Comment by imalavins** [comment]
![https://www.pexels.com/photo/people-in-boat-near-water-dam-1259924/](https://images.pexels.com/photos/1259924/pexels-photo-1259924.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260)

https://flic.kr/p/dtLWPE

https://flic.kr/p/of2TEy

https://flic.kr/p/6zwCj5
