### ISSUE TITLE
Create the jumbotron for index page

### ISSUE THREAD

**Issue by davieiycode** [bppugm/icst-2019#5]

**Comment by davieiycode** [comment]
![https://www.freepik.com/free-vector/dynamic-colorful-vibrant-wave-colorful-background_3725644.htm](https://image.freepik.com/free-vector/dynamic-colorful-vibrant-wave-colorful-background_1017-16948.jpg)
![https://www.freepik.com/free-vector/abstract-background-mobile-instagram-stories_3190092.htm](https://image.freepik.com/free-vector/abstract-background-mobile-instagram-stories_1361-732.jpg)
![https://www.freepik.com/free-vector/colorful-abstract-banners_3085167.htm](https://image.freepik.com/free-vector/colorful-abstract-banners_1082-110.jpg)
![https://www.shutterstock.com/image-vector/geometric-background-dynamic-shapes-composition-eps10-1216421962?irgwc=1&utm_medium=Affiliate&utm_campaign=Freepik%20Company%2C%20S.L.&utm_source=39422&utm_term=](https://image.shutterstock.com/image-vector/geometric-background-dynamic-shapes-composition-450w-1216421962.jpg)
![https://dribbble.com/shots/4031241-Homepage-Banner](https://cdn.dribbble.com/users/20488/screenshots/4031241/venture_landing_page.png)
[http://tencon2018.org/](http://tencon2018.org/)
[http://design-studio.io/10-ui-ux-design-trends-for-2019/](http://design-studio.io/10-ui-ux-design-trends-for-2019/)

**Comment by JordanTranchina** [comment]
Hey y'all! I'm a UX Designer. Want me to take a stab here? Let me know by assigning me to the issue.

Cheers,
Jordan
